###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Miguel Hidalgo",
    "age":75,
    "email": "miguel@corre.com"
}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/654480fd002fcc1c2b8056cd HTTP/1.1

###
PUT http://localhost:9000/api/users/6544855aa2d0053ff15efcde HTTP/1.1
Content-Type: application/json

{
    "name": "Juanito Perez",
    "age":75,
    "email": "miguel@corre.com"
}

###
DELETE http://localhost:9000/api/users/6544855ba2d0053ff15efce2 HTTP/1.1


